### ISSUE TITLE
Cannot unzip the file because of 0x80004005

### ISSUE THREAD

**Issue by Firestar-Reimu** [manjaro/release-review#1]
I installed `manjaro-kde-21.0-minimal-210220-linux510.iso.zip` but when I unzip the file, it pops out an error: 0x80004005

`regsvr32 Initpki.dll` also leads to error

Even 7zip cannot unzip it.

**Comment by hphilm** [comment]
Seems you are using Windows for trying to extract the file. We used `zip` on Linux to split the file. Also did you downloaded `manjaro-kde-21.0-minimal-210220-linux510.iso.z01` and placed it into the same download directory? You may want additionally to check if the downloaded files match the sha256 sums.

**Comment by hphilm** [comment]
@1900011604 see also [here](https://support.firmex.com/hc/en-us/articles/204579673-Downloads-with-multiple-parts-z01-and-z02-files-).

**Comment by Firestar-Reimu** [comment]
Thanks! The problem is solved! I did not download manjaro-kde-21.0-minimal-210220-linux510.iso.z01 and placed it into the same download directory, I was even thinking that my Windows has broken.

Don't you put them in the OSDN archive?

**Comment by hphilm** [comment]
Reviews and Previews we don't upload to OSDN anymore. Upload speed is to slow. However you may find releases on Sourceforge.
