### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by TolyanDimov** [manjaro/release-review#17]
I am new to Linux.
Error installing Manjaro 21.1 KDE.
During the installation of the system, approximately in the middle, the installation aborts with an error. 
You can reproduce the error by specifying: user_name = Git; computer_name = Hub

I have done the installation several times. I noticed that the installation only breaks if you use a username like Git.

**Comment by Firestar-Reimu** [comment]
I think it is because user name requires a all-non-capital-letter name like `git`
