### ISSUE TITLE
latest SHA1 sums do not match isos for download

### ISSUE THREAD

**Issue by aaronwi** [manjaro/release-review#8]
eg: 
 manjaro-kde-21.0.7-210614-linux510.iso     sha1sum results in 43f0f573d6c5d089cd280b622f228d1ea2933cf8

listed checksum is 9cd47445831dfd6770d4af0bbd9cdef16faf9934

**Comment by hphilm** [comment]
Is it still the case with newer builds?

**Comment by urgentus** [comment]
The same error:
manjaro-xfce-21.1-stable-staging-minimal-210720-linux513.iso - 386eb9ec93113346da6b62c91a0a2ee0b7a62ff5930c9e1c71dddf2153dcd0db 

gtkhash calculate:
55b6a07e03dbc7d4772eb1ae62c9da5a3b8448285f70a455478984658423f4a2
